application: abstract-flame-92723
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: Shop.app

libraries:
- name: jinja2
  version: latest

#http://localhost:8000
#http://localhost:8080